FROM rust:latest AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin openai-proxy

FROM ubuntu:latest
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates

COPY --from=builder /app/target/release/openai-proxy /app/openai-proxy
WORKDIR /app
EXPOSE 8100
CMD ["/app/openai-proxy"]


